-- ==========================================
-- MATCHUP - SUPABASE DATABASE SCHEMA
-- ==========================================
-- Version: 1.0.0
-- Created: 2025
-- Description: Complete database schema for MatchUp dating application
-- 
-- EXECUTION ORDER:
-- 1. Tables (with foreign keys)
-- 2. Indexes (performance optimization)
-- 3. Triggers (automatic updated_at)
-- 4. Enable RLS (Row Level Security)
-- 5. RLS Policies (security rules)
-- 6. Seed Data (test data)
--
-- IMPORTANT: Execute this script in Supabase SQL Editor
-- ==========================================

-- ==========================================
-- SECTION 1: TABLES
-- ==========================================
-- Order respects foreign key dependencies
-- All tables include audit columns: created_at, updated_at

-- Drop existing tables if they exist (for clean install)
drop table if exists public.message cascade;
drop table if exists public.matches cascade;
drop table if exists public.interest cascade;
drop table if exists public.gallery cascade;
drop table if exists public.users cascade;

-- Table: users
-- Main user profile table linked to Supabase Auth
create table public.users (
  id uuid references auth.users on delete cascade not null primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  
  -- Basic Information
  username text not null unique,
  email text not null unique,
  gender text check (gender in ('male', 'female', 'other')),
  
  -- Profile Media
  image text, -- Main profile picture URL
  
  -- Personal Details
  age integer check (age >= 18 and age <= 100),
  date_of_birth date,
  city text,
  country text,
  bio text check (length(bio) <= 500),
  
  -- Professional Information
  job_title text,
  company text,
  education text,
  
  -- Physical Attributes
  height_cm integer check (height_cm >= 100 and height_cm <= 250),
  
  -- Account Status
  is_active boolean default true,
  is_verified boolean default false,
  last_active timestamp with time zone default now()
);

-- Add comment to table
comment on table public.users is 'Main user profile table with all user information';

-- Table: gallery
-- User photo gallery (up to 6 photos per user)
create table public.gallery (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  
  users_id uuid references public.users(id) on delete cascade not null,
  image text not null, -- Photo URL from Supabase Storage
  position integer check (position >= 1 and position <= 6), -- Display order
  
  -- Unique constraint: one position per user
  unique(users_id, position)
);

comment on table public.gallery is 'User photo gallery with maximum 6 photos per user';

-- Table: interest
-- User interests/hobbies for matching
create table public.interest (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  
  users_id uuid references public.users(id) on delete cascade not null,
  name text not null check (length(name) <= 50)
);

comment on table public.interest is 'User interests and hobbies for better matching';

-- Table: matches
-- Match requests between users (like/dislike/match)
create table public.matches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  
  sender_match uuid references public.users(id) on delete cascade not null,
  receiver_match uuid references public.users(id) on delete cascade not null,
  
  -- Match status: null (pending), true (accepted/matched), false (rejected)
  accepted boolean,
  
  -- Prevent self-matching and duplicate matches
  check (sender_match != receiver_match),
  unique(sender_match, receiver_match)
);

comment on table public.matches is 'Match requests and their acceptance status';

-- Table: message
-- Chat messages between matched users
create table public.message (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  
  sender_id uuid references public.users(id) on delete cascade not null,
  destination_users uuid references public.users(id) on delete cascade not null,
  
  message text not null check (length(message) <= 1000),
  seen boolean default false,
  
  -- Prevent self-messaging
  check (sender_id != destination_users)
);

comment on table public.message is 'Chat messages between matched users';

-- ==========================================
-- SECTION 2: INDEXES
-- ==========================================
-- Optimized indexes for common query patterns

-- Users table indexes
create index idx_users_gender on public.users(gender);
create index idx_users_city on public.users(city);
create index idx_users_age on public.users(age);
create index idx_users_is_active on public.users(is_active);
create index idx_users_last_active on public.users(last_active desc);

-- Gallery table indexes
create index idx_gallery_users_id on public.gallery(users_id);
create index idx_gallery_users_position on public.gallery(users_id, position);

-- Interest table indexes
create index idx_interest_users_id on public.interest(users_id);
create index idx_interest_name on public.interest(name);

-- Matches table indexes
create index idx_matches_sender on public.matches(sender_match);
create index idx_matches_receiver on public.matches(receiver_match);
create index idx_matches_accepted on public.matches(accepted);
create index idx_matches_sender_receiver on public.matches(sender_match, receiver_match);
create index idx_matches_pending on public.matches(receiver_match) where accepted is null;
create index idx_matches_confirmed on public.matches(sender_match, receiver_match) where accepted = true;

-- Message table indexes
create index idx_message_sender on public.message(sender_id);
create index idx_message_destination on public.message(destination_users);
create index idx_message_seen on public.message(seen);
create index idx_message_created_at on public.message(created_at desc);
create index idx_message_unread on public.message(destination_users, sender_id, seen) where seen = false;
create index idx_message_conversation on public.message(sender_id, destination_users, created_at desc);

-- ==========================================
-- SECTION 3: TRIGGERS (updated_at)
-- ==========================================

-- Function to automatically update updated_at column
create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Add comment to function
comment on function public.update_updated_at_column() is 'Automatically updates the updated_at timestamp on row update';

-- Create triggers for all tables
create trigger update_users_updated_at 
  before update on public.users
  for each row execute function public.update_updated_at_column();

create trigger update_gallery_updated_at 
  before update on public.gallery
  for each row execute function public.update_updated_at_column();

create trigger update_interest_updated_at 
  before update on public.interest
  for each row execute function public.update_updated_at_column();

create trigger update_matches_updated_at 
  before update on public.matches
  for each row execute function public.update_updated_at_column();

create trigger update_message_updated_at 
  before update on public.message
  for each row execute function public.update_updated_at_column();

-- ==========================================
-- SECTION 4: ENABLE ROW LEVEL SECURITY
-- ==========================================

alter table public.users enable row level security;
alter table public.gallery enable row level security;
alter table public.interest enable row level security;
alter table public.matches enable row level security;
alter table public.message enable row level security;

-- ==========================================
-- SECTION 5: RLS POLICIES
-- ==========================================

-- ========================================
-- USERS TABLE POLICIES
-- ========================================

-- Policy: Users can view all profiles (for discovery)
create policy "Users can view all profiles"
  on public.users for select
  to authenticated
  using (true);

-- Policy: Users can insert their own profile
create policy "Users can insert own profile"
  on public.users for insert
  to authenticated
  with check (auth.uid() = id);

-- Policy: Users can update only their own profile
create policy "Users can update own profile"
  on public.users for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Policy: Users can delete their own profile
create policy "Users can delete own profile"
  on public.users for delete
  to authenticated
  using (auth.uid() = id);

-- ========================================
-- GALLERY TABLE POLICIES
-- ========================================

-- Policy: Anyone can view gallery photos
create policy "Users can view all gallery"
  on public.gallery for select
  to authenticated
  using (true);

-- Policy: Users can insert photos to their own gallery
create policy "Users can insert own gallery"
  on public.gallery for insert
  to authenticated
  with check (auth.uid() = users_id);

-- Policy: Users can update their own gallery photos
create policy "Users can update own gallery"
  on public.gallery for update
  to authenticated
  using (auth.uid() = users_id)
  with check (auth.uid() = users_id);

-- Policy: Users can delete their own gallery photos
create policy "Users can delete own gallery"
  on public.gallery for delete
  to authenticated
  using (auth.uid() = users_id);

-- ========================================
-- INTEREST TABLE POLICIES
-- ========================================

-- Policy: Anyone can view all interests
create policy "Users can view all interests"
  on public.interest for select
  to authenticated
  using (true);

-- Policy: Users can insert their own interests
create policy "Users can insert own interests"
  on public.interest for insert
  to authenticated
  with check (auth.uid() = users_id);

-- Policy: Users can update their own interests
create policy "Users can update own interests"
  on public.interest for update
  to authenticated
  using (auth.uid() = users_id)
  with check (auth.uid() = users_id);

-- Policy: Users can delete their own interests
create policy "Users can delete own interests"
  on public.interest for delete
  to authenticated
  using (auth.uid() = users_id);

-- ========================================
-- MATCHES TABLE POLICIES
-- ========================================

-- Policy: Users can view matches where they are involved (sender or receiver)
create policy "Users can view own matches"
  on public.matches for select
  to authenticated
  using (auth.uid() in (sender_match, receiver_match));

-- Policy: Users can create match requests (like someone)
create policy "Users can insert matches"
  on public.matches for insert
  to authenticated
  with check (auth.uid() = sender_match);

-- Policy: Users can update matches they received (accept/reject)
create policy "Users can update received matches"
  on public.matches for update
  to authenticated
  using (auth.uid() = receiver_match);

-- Policy: Users can delete matches they sent
create policy "Users can delete sent matches"
  on public.matches for delete
  to authenticated
  using (auth.uid() = sender_match);

-- ========================================
-- MESSAGE TABLE POLICIES
-- ========================================

-- Policy: Users can view messages where they are sender or receiver
create policy "Users can view own messages"
  on public.message for select
  to authenticated
  using (auth.uid() in (sender_id, destination_users));

-- Policy: Users can send messages to their matches
create policy "Users can insert messages"
  on public.message for insert
  to authenticated
  with check (
    auth.uid() = sender_id and
    exists (
      select 1 from public.matches
      where (sender_match = auth.uid() and receiver_match = destination_users)
         or (receiver_match = auth.uid() and sender_match = destination_users)
      and accepted = true
    )
  );

-- Policy: Users can update messages they received (mark as seen)
create policy "Users can update received messages"
  on public.message for update
  to authenticated
  using (auth.uid() = destination_users);

-- ==========================================
-- SECTION 6: SEED DATA
-- ==========================================
-- Test users with diverse profiles for development

-- Note: Before inserting seed data, you must create auth users manually
-- in Supabase Dashboard or via API with the same UUIDs

-- Sample users (UUIDs are examples - replace with actual auth user IDs)
insert into public.users (id, username, email, gender, age, date_of_birth, city, country, bio, job_title, company, education, height_cm, image) values
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'sophie_martin', 'sophie.martin@example.com', 'female', 28, '1996-03-15', 'Paris', 'France', 'Passionnée de voyage et de photographie. Toujours à la recherche de nouvelles aventures ! 📸✨', 'Designer UX/UI', 'Startup Tech', 'Master Design', 165, 'https://i.pravatar.cc/300?img=1'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'julien_dubois', 'julien.dubois@example.com', 'male', 32, '1992-07-22', 'Lyon', 'France', 'Développeur le jour, chef cuisinier le soir. Amateur de bonne cuisine et de musique jazz 🎷🍝', 'Lead Developer', 'Scale-up AI', 'Ingénieur Informatique', 178, 'https://i.pravatar.cc/300?img=12'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'emma_rousseau', 'emma.rousseau@example.com', 'female', 26, '1998-11-08', 'Bordeaux', 'France', 'Architecte d''intérieur avec une passion pour l''art moderne. Yoga et méditation 🧘‍♀️🎨', 'Architecte', 'Atelier Design', 'École d''Architecture', 170, 'https://i.pravatar.cc/300?img=5'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'thomas_laurent', 'thomas.laurent@example.com', 'male', 29, '1995-05-12', 'Marseille', 'France', 'Entrepreneur passionné de tech et d''innovation. Week-end en montagne obligatoire ⛰️💼', 'CEO', 'Ma Startup', 'École de Commerce', 182, 'https://i.pravatar.cc/300?img=15'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', 'marie_garcia', 'marie.garcia@example.com', 'female', 31, '1993-09-20', 'Toulouse', 'France', 'Marketing Manager qui adore les concerts et les festivals. Toujours partante pour découvrir de nouveaux artistes 🎵🎪', 'Marketing Manager', 'Grande Entreprise', 'Master Marketing', 168, 'https://i.pravatar.cc/300?img=9'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16', 'lucas_bernard', 'lucas.bernard@example.com', 'male', 27, '1997-02-14', 'Nantes', 'France', 'Data Scientist et runner passionné. Marathon et trail le week-end 🏃‍♂️📊', 'Data Scientist', 'FinTech', 'Doctorat Math', 175, 'https://i.pravatar.cc/300?img=18'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17', 'chloe_petit', 'chloe.petit@example.com', 'female', 25, '1999-06-30', 'Lille', 'France', 'Journaliste lifestyle et blogueuse voyage. La vie est trop courte pour ne pas explorer le monde 🌍✈️', 'Journaliste', 'Magazine Mode', 'Master Journalisme', 163, 'https://i.pravatar.cc/300?img=20'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18', 'maxime_roux', 'maxime.roux@example.com', 'male', 34, '1990-12-03', 'Strasbourg', 'France', 'Avocat d''affaires amateur de vin et de gastronomie. Membre d''un club d''œnologie 🍷⚖️', 'Avocat', 'Cabinet Juridique', 'Master Droit', 180, 'https://i.pravatar.cc/300?img=22'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', 'lea_moreau', 'lea.moreau@example.com', 'female', 30, '1994-04-18', 'Nice', 'France', 'Médecin urgentiste qui aime profiter de chaque instant libre. Plongée et paddle en Méditerranée 🏥🌊', 'Médecin', 'CHU', 'Doctorat Médecine', 172, 'https://i.pravatar.cc/300?img=24'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20', 'alexandre_simon', 'alexandre.simon@example.com', 'male', 33, '1991-08-25', 'Montpellier', 'France', 'Product Manager passionné de sport. Tennis, surf et trail running. Toujours en quête de nouvelles expériences 🎾🏄‍♂️', 'Product Manager', 'Tech Company', 'Ingénieur', 185, 'https://i.pravatar.cc/300?img=26'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a21', 'camille_fournier', 'camille.fournier@example.com', 'female', 27, '1997-10-07', 'Rennes', 'France', 'Professeure de yoga et coach bien-être. Végétarienne convaincue et amoureuse de la nature 🌱🧘‍♀️', 'Coach Yoga', 'Studio Wellness', 'Formation Yoga', 166, 'https://i.pravatar.cc/300?img=28'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'antoine_girard', 'antoine.girard@example.com', 'male', 29, '1995-01-11', 'Grenoble', 'France', 'Ingénieur en énergies renouvelables et skieur passionné. Engagé pour l''environnement 🌿⛷️', 'Ingénieur', 'Green Energy', 'Ingénieur Énergie', 177, 'https://i.pravatar.cc/300?img=30'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a23', 'laura_fontaine', 'laura.fontaine@example.com', 'female', 26, '1998-05-19', 'Dijon', 'France', 'Community Manager créative. Netflix addict et foodie dans l''âme. Toujours à la recherche du meilleur brunch 🍳☕', 'Community Manager', 'Agence Com', 'Master Communication', 169, 'https://i.pravatar.cc/300?img=32'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a24', 'mathieu_vincent', 'mathieu.vincent@example.com', 'male', 31, '1993-03-28', 'Reims', 'France', 'Photographe professionnel spécialisé en portrait. Passionné de cinéma et de séries. Canon ou Nikon ? 📷🎬', 'Photographe', 'Freelance', 'École Photo', 183, 'https://i.pravatar.cc/300?img=34'),
  
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a25', 'clara_mercier', 'clara.mercier@example.com', 'female', 28, '1996-07-16', 'Angers', 'France', 'RH dans la tech avec une passion pour la danse contemporaine. Lectures et musées le dimanche 💃📚', 'Responsable RH', 'Tech Startup', 'Master RH', 167, 'https://i.pravatar.cc/300?img=36');

-- Sample gallery photos
insert into public.gallery (users_id, image, position) values
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'https://i.pravatar.cc/400?img=1', 1),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'https://i.pravatar.cc/400?img=2', 2),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'https://i.pravatar.cc/400?img=12', 1),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'https://i.pravatar.cc/400?img=13', 2),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'https://i.pravatar.cc/400?img=5', 1),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'https://i.pravatar.cc/400?img=15', 1),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', 'https://i.pravatar.cc/400?img=9', 1);

-- Sample interests
insert into public.interest (users_id, name) values
  -- Sophie
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Photographie'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Voyage'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Art'),
  -- Julien
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'Cuisine'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'Jazz'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'Programmation'),
  -- Emma
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'Design'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'Yoga'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'Art moderne'),
  -- Thomas
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'Entrepreneuriat'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'Randonnée'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'Tech'),
  -- Marie
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', 'Concerts'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', 'Festivals'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', 'Marketing'),
  -- Lucas
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16', 'Running'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16', 'Data Science'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16', 'Trail'),
  -- Chloé
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17', 'Journalisme'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17', 'Voyage'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17', 'Blogging'),
  -- Maxime
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18', 'Oenologie'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18', 'Gastronomie'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18', 'Droit'),
  -- Léa
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', 'Plongée'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', 'Paddle'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', 'Médecine'),
  -- Alexandre
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20', 'Tennis'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20', 'Surf'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20', 'Trail'),
  -- Camille
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a21', 'Yoga'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a21', 'Bien-être'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a21', 'Nature'),
  -- Antoine
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'Ski'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'Écologie'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'Montagne'),
  -- Laura
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a23', 'Social Media'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a23', 'Food'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a23', 'Netflix'),
  -- Mathieu
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a24', 'Photographie'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a24', 'Cinéma'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a24', 'Séries'),
  -- Clara
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a25', 'Danse'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a25', 'Lecture'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a25', 'Musées');

-- Sample matches (some pending, some accepted)
insert into public.matches (sender_match, receiver_match, accepted) values
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', true),  -- Julien & Sophie matched
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', true),  -- Thomas & Emma matched
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', null),  -- Lucas -> Marie pending
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17', null),  -- Maxime -> Chloé pending
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', true),  -- Alexandre & Léa matched
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a21', null),  -- Antoine -> Camille pending
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a24', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a23', true),  -- Mathieu & Laura matched
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a25', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a24', null);  -- Clara -> Mathieu pending

-- Sample messages (only between matched users)
insert into public.message (sender_id, destination_users, message, seen) values
  -- Conversation Julien & Sophie
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Salut Sophie ! J''ai vu que tu adores la photographie, moi aussi ! 📸', true),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'Hey Julien ! Oui c''est ma passion. Tu as un appareil préféré ?', true),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Je suis plutôt Canon, et toi ?', true),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'Sony mirrorless pour moi ! Plus compact pour voyager', false),
  
  -- Conversation Thomas & Emma
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'Ton profil d''architecte est impressionnant ! Tu as un projet préféré ?', true),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'Merci ! J''adore les projets de lofts contemporains. Et toi, ta startup ?', false),
  
  -- Conversation Alexandre & Léa
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', 'Salut Léa ! Médecin urgentiste, ça doit être intense !', true),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20', 'Oui très ! Mais ça me laisse le temps de profiter de la mer 🌊', true),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19', 'J''aimerais bien essayer le paddle avec toi un jour !', false),
  
  -- Conversation Mathieu & Laura
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a24', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a23', 'Hey Laura ! Community Manager et foodie, combo parfait 😄', true),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a23', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a24', 'Haha merci ! Tu fais des photos culinaires parfois ?', false);

-- ==========================================
-- SECTION 7: VERIFICATION QUERIES
-- ==========================================
-- Run these queries to verify the installation

-- Check tables
select 
  schemaname,
  tablename,
  tableowner
from pg_tables
where schemaname = 'public'
order by tablename;

-- Check RLS enabled
select
  schemaname,
  tablename,
  rowsecurity
from pg_tables
where schemaname = 'public'
order by tablename;

-- Check policies
select
  schemaname,
  tablename,
  policyname,
  permissive,
  roles,
  cmd
from pg_policies
where schemaname = 'public'
order by tablename, policyname;

-- Check triggers
select
  trigger_schema,
  trigger_name,
  event_object_table,
  action_statement
from information_schema.triggers
where trigger_schema = 'public'
order by event_object_table, trigger_name;

-- Check indexes
select
  schemaname,
  tablename,
  indexname,
  indexdef
from pg_indexes
where schemaname = 'public'
order by tablename, indexname;

-- Count records in each table
select 'users' as table_name, count(*) as record_count from public.users
union all
select 'gallery', count(*) from public.gallery
union all
select 'interest', count(*) from public.interest
union all
select 'matches', count(*) from public.matches
union all
select 'message', count(*) from public.message;

-- ==========================================
-- END OF SCHEMA
-- ==========================================
-- Successfully created MatchUp database schema
-- Total tables: 5 (users, gallery, interest, matches, message)
-- Total indexes: 20+ (optimized for common queries)
-- RLS enabled: All tables
-- Policies: 23 (comprehensive security)
-- Triggers: 5 (automatic updated_at)
-- Seed data: 15 users + related data
--
-- Next steps:
-- 1. Configure Storage bucket "matchUp" in Supabase Dashboard
-- 2. Set up Storage policies for image uploads
-- 3. Get your Supabase URL and anon key
-- 4. Update Flutter configuration with your credentials
-- ==========================================
